POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "kalle",
  "password": "kalle",
  "email": "kallejee@test.com",
  "name": "Kalle Penttinen",
  "isSuperadmin": true
}